steps:
  # see https://www.npmjs.com/package/editorconfig-checker
  #- id: eclint
  #  name: "e53e225/editorconfig-checker"


  - id: "Building image from Dockerfile"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/go-ci:$SHORT_SHA','-f','Dockerfile','.'] # O $SHORT_SHA é para gerar um nome de imagem diferente para cada imagem baseado no commit  

  - id: "Pushing image"  
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/go-ci:$SHORT_SHA']